### ISSUE TITLE
UI?

### ISSUE THREAD

**Issue by timkpaine** [nteract/bookstore#169]
Is there a UI for this? Would it make sense to  add this as a backend for my auto version extension? https://github.com/timkpaine/jupyterlab_autoversion

**Comment by mpacer** [comment]
I'd be open to discussing this! 

What features would you need implemented to make it work as a backend for your extension?

I'd love to hear thoughts from @willingc @rgbkrk @MSeal @stormpython and others too.

**Comment by MSeal** [comment]
I think the original intention was to make bookstore a viable option as a backend for features like auto-version or other plugins to notebook stacks. Given there's not a fairly stable base we're using with the recent releases I think it makes sense to gather requirements and capabilities for existing tools to make use of bookstore, rather than planning a new UI in-and-of itself at this time.

**Comment by timkpaine** [comment]
@mpacer @MSeal let me see if i can blend mine, its extremely light weight so I assume its easy. Is there any plan to support other backends/allow for custom backends like sql blobs or mongo?

**Comment by MSeal** [comment]
Yes the intention was to support other backends in the future. It was just starting with what we use internally first.

**Comment by timkpaine** [comment]
@MSeal I figured. Internally we use a globally replicated object store that automatically versions all notebooks on save, but `jupyterlab_autoversion` is my "poor man's" external version of the same type of feature. But if i start to generalize, will want to generalize to arbitrary backends.

Will try to hook in this project and circle back sometime next week.
