### ISSUE TITLE
clone a specific version notebook 

### ISSUE THREAD

**Issue by rakeshpatri** [nteract/bookstore#172]
I dont find a way to specify versionId from s3 to the clone API, so that i can fetch a specific versioned notebook.
Let me know if there is way to do this in current implementation.

**Comment by mpacer** [comment]
There is no way currently but it is planned to support this.

One of the barriers has been in testing this. We use minio for our integration test, and it does not support versioned buckets and so we may need to either only unit test this functionality or switch to actually using S3 for our integration tests (which introduces its own set of complexities).

**Comment by mpacer** [comment]
@rakeshpatri This is now supported as of 2.5.1, see #176 for the implementation details and https://bookstore.readthedocs.io/en/latest/changelog.html#id3 (version 2.5.1 for the details on how to use it). 

Feel free to comment on the issue or create a new one if you have remaining issues, but I'm going to close this since it has been addressed.
