### ISSUE TITLE
Create config that is shared across Archiver, Publisher, etc.

### ISSUE THREAD

**Issue by rgbkrk** [nteract/bookstore#7]
Since we're going to want to use the same S3 settings across the Jupyter extension for publishing and the archival contents manager, we need to be able to instantiate a config object that can be shared amongst these.

Right now this is encapsulated in `bookstore/bookstore_config.py` as `BookstoreS3Settings` and `Bookstore `. What I need is how we'll rely on these within `BookstoreContentsArchiver` and how we'll set them up in the `jupyter_notebook_config.py` (example in the `README`).

cc @mpacer

**Comment by mpacer** [comment]
In #8 I put together what should be a basic example of how you could set these things up (I also updated the example configs to take that into account). It will need to look slightly different for handlers (since handlers are not themselves `LoggingConfigurable`s we cannot pass them down through `parent=self`). 

Let me know if there's anything more that would benefit from clarification :)

**Comment by rgbkrk** [comment]
This is now done for the archiver, @mpacer and I talked a bit in chat about how we'll handle this for the handlers case (since, as M stated, we can't hook in with `parent=self` within `__init__`).
